apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron
  namespace: test
spec:
  schedule: "5 8 * * 0"  # At 08:05 on Sundays
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: test-cron
              image: ghcr.io/kj800x/test-repo:commit-$SHA
              env:
                - name: IS_A_CRON_JOB
                  value: "true"

